dependencies:
  - google-api-core           2.19.0
  - google-api-python-client  2.131.0
  - google-auth               2.29.0
  - google-auth-httplib2      0.2.0
  - googleapis-common-protos  1.63.0
  - mysql-connector-python    8.4.0
  - numpy                     1.26.4
  - pandas                    2.2.2
  - SQLAlchemy                2.0.30
  - streamlit                 1.35.0
